### ISSUE TITLE
Spotify refresh token support

### ISSUE THREAD

**Issue by dustinkerstein** [StanvBaarsen/SpotifyTracker#1]
Hey! I just [forked](https://github.com/dustinkerstein/SpotifyTracker_playlistRotate) your awesome project and made some small tweaks for a friend who was looking for a way to automatically rotate through a few playlists after X number of songs play. It's working pretty well so far. Thanks for providing such a straightforward browser-based Spotify client. I was curious, have you looked into adding support for [refresh tokens](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/)? Currently the session will time out at 60 minutes. I could maybe take a stab at it, but it would probably turn out pretty hacky.

**Comment by StanvBaarsen** [comment]
Hey, it’s nice to know you’re appreciating my work! Good to see the adjustments you did in your fork, I might use your translations if you don’t mind.

As for the refresh tokens, I looked into those when building the app, but for some reason (which I cannot recall), I decided that those weren’t suitable for the project. But, looking at the link you sent, it seems very doable and I’ll take a second look at it soon! Thanks for letting me know

Op 5 sep. 2022 om 01:02 heeft Dustin Kerstein ***@***.***> het volgende geschreven:

﻿

Hey! I just forked<https://github.com/dustinkerstein/SpotifyTracker_playlistRotate> your awesome project and made some small tweaks for a friend who was looking for a way to automatically rotate through a few playlists after X number of songs play. It's working pretty well so far. Thanks for providing such a straightforward browser-based Spotify client. I was curious, have you looked into adding support for refresh tokens<https://developer.spotify.com/documentation/general/guides/authorization/code-flow/>? Currently the session will time out at 60 minutes. I could maybe take a stab at it, but it would probably turn out pretty hacky.

**Comment by dustinkerstein** [comment]
Awesome! And of course, you're welcome to use my translations. Also feel free to take any code from the [Google Apps Script branch](https://github.com/dustinkerstein/SpotifyTracker_playlistRotate/tree/gas) as that's where I'll probably be continuing to make some tweaks. As it currently stands, it's functional as a Google Apps Script project. This provides free hosting (and would also provide server-side functions if any are desired in the future). Firebase would be a more robust solution but GAS is a bit easier to get setup. Thanks again, and let me know if there's anything I can help with.

**Comment by StanvBaarsen** [comment]
Interesting! I've never heard of GAS before, but I'll look into it as well, sounds great

As for the refresh tokens: the good news is that I managed to implement them! The changes are live now. The bad news: apparently, I restructured the files in the project a few months ago without committing the changes, meaning that it could get annoying to merge the changes to your fork, apologies!

**Comment by dustinkerstein** [comment]
Nice! Thanks for digging into that. No worries on the merge :)
